import Head from 'next/head'
import Image from 'next/image'
import MeetupList from '../components/meetups/MeetupList'
import styles from '../styles/Home.module.css'

export default function Home() {
  const dummy=[
    {
      id:'m1',
      title:"A First Meetup",
      image:'https://media.istockphoto.com/photos/hot-air-balloons-flying-over-the-botan-canyon-in-turkey-picture-id1297349747?b=1&k=20&m=1297349747&s=170667a&w=0&h=oH31fJty_4xWl_JQ4OIQWZKP8C6ji9Mz7L4XmEnbqRU=',
      address:'Some address 5,1234 Some City',
      description:'This is a first Meetup'
    },
    {
      id:'m2',
      title:"A Second Meetup",
      image:'https://media.istockphoto.com/photos/taj-mahal-mausoleum-in-agra-picture-id1146517111?k=20&m=1146517111&s=612x612&w=0&h=vHWfu6TE0R5rG6DJkV42Jxr49aEsLN0ML-ihvtim8kk=',
      address:'Some address 15,12 Some City',
      description:'This is a second Meetup'
    }
  ]
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MeetupList meetups={dummy}/>
    </div>
  )
}
